import obseq.proof.state_helpers

/-!
# `obseq.proof.const_existing`

Local compiler-correctness lemmas for the existing-destination word-constant
fragment.

Unlike the fresh fragment, the existing destination may now be an arbitrary
projected place. The proof therefore tracks the base layout and the resolved
projection offset explicitly, while `StateSim` itself remains keyed by base
places only.
-/

namespace obseq.proof

open obseq
open obseq.mirlite
open obseq.oseair hiding State Result
open obseq.compile
open scoped obseq.notation

variable {A_m : mirlite.AllocatorSpec} {A_o : oseair.AllocatorSpec}

structure ConstExistingCtx where
  /-- The destination place. -/
  dst : mirlite.Place
  /-- The register where the destination base is currently mapped. -/
  reg : Register
  /-- The constant value to be written. -/
  n : Word
  /-- The compiler state. -/
  cs : CompilerState
  /-- The instructions generated by the compiler state are empty. -/
  h_instrs : CompilerEmpty cs
  /-- The layout of the base where the destination resides. -/
  baseLayout : LayoutTy
  /-- The offset within the base layout where the destination resides. -/
  off : Word
  /-- The destination base is present in the compiler place map, mapped to `reg` and `baseLayout`. -/
  h_lookup : BaseReady cs dst.base reg baseLayout
  /-- The resolved path within the base layout for the destination. -/
  h_path : layoutResolvePath baseLayout dst.path = some (off, LayoutTy.NatL)

namespace ConstExistingCtx

/-- A temporary register used for intermediate computations. -/
def tmpReg (ctx : ConstExistingCtx) : Register :=
  Register.R ctx.cs.nextReg

/-- The statement _place = ConstOp(n) for an existing destination place. -/
def stmt (ctx : ConstExistingCtx) : mirlite.Stmt :=
  mirlite.Stmt.Assgn (obseq.notation.placeExpr ctx.dst) (obseq.notation.constRhs ctx.n)

/-- The compiled instructions for the ConstOp(n) for an existing destination place. -/
def compiled (ctx : ConstExistingCtx) : oseair.Prog :=
  (compileStmt ctx.cs ctx.stmt).instrs

theorem instrs_nil (ctx : ConstExistingCtx) : ctx.cs.instrs = [] :=
  ctx.h_instrs

/-- The compiled instructions for the ConstOp(n) for an existing destination place. -/
@[simp] theorem compiled_eq
  (ctx : ConstExistingCtx) :
  ctx.compiled =
    if ctx.off = 0 then
      [oseair.Instr.CStore TyVal.NatTy [oseair.Val.Dat ctx.n] ctx.reg]
    else
      [oseair.Instr.Assgn ctx.tmpReg (oseair.Rhs.MutBorOffset ctx.reg ctx.off),
       oseair.Instr.CStore TyVal.NatTy [oseair.Val.Dat ctx.n] ctx.tmpReg,
       oseair.Instr.Die ctx.tmpReg] := by
  by_cases h_off : ctx.off = 0
  · have h_place :
        placeToReg ctx.cs ctx.dst mirlite.RefKind.Mut (some LayoutTy.NatL) =
          { reg := ctx.reg, layout := LayoutTy.NatL, cleanup := [], cs := ctx.cs } := by
      unfold placeToReg
      rw [ctx.h_lookup]
      simp [ctx.h_path, h_off]
    unfold ConstExistingCtx.compiled ConstExistingCtx.stmt compileStmt
    simpa [h_off] using
      (by
        simp [h_place, emit, cleanupInstrs, obseq.notation.placeExpr,
      obseq.notation.constRhs, ctx.instrs_nil]
      )
  · have h_place :
        placeToReg ctx.cs ctx.dst mirlite.RefKind.Mut (some LayoutTy.NatL) =
          { reg := ctx.tmpReg,
            layout := LayoutTy.NatL,
            cleanup := [ctx.tmpReg],
            cs :=
              { nextReg := ctx.cs.nextReg + 1,
                placeMap := ctx.cs.placeMap,
                instrs := ctx.cs.instrs ++
                  [oseair.Instr.Assgn ctx.tmpReg (oseair.Rhs.MutBorOffset ctx.reg ctx.off)] } } := by
      unfold placeToReg
      rw [ctx.h_lookup]
      simp [ctx.h_path, h_off, ConstExistingCtx.tmpReg, freshReg, emit]
    unfold ConstExistingCtx.compiled ConstExistingCtx.stmt compileStmt
    simpa [h_off] using
      (by
        simp [h_place, emit, cleanupInstrs, obseq.notation.placeExpr,
      obseq.notation.constRhs, ConstExistingCtx.tmpReg, ctx.instrs_nil]
      )

end ConstExistingCtx

namespace ConstExisting

abbrev LocalSim
  (ctx : ConstExistingCtx)
  (ρa : AddrRenameMap)
  (ρt : TagRenameMap)
  (s_mir : mirlite.State)
  (s_osea : oseair.State) : Prop :=
  StateSim ctx.cs.placeMap ρa ρt s_mir s_osea

theorem mirlite_step_inv
  (ctx : ConstExistingCtx)
  (s_mir : mirlite.State)
  (s_mir_next : mirlite.State)
  (prog_mir : mirlite.Prog)
  (addr tag : Word)
  (h_env : s_mir.env.lookup ctx.dst.base = some (addr, layoutToTyVal ctx.baseLayout, tag))
  (h_start : StartsAt prog_mir s_mir.pc [ctx.stmt])
  (h_step : mirlite.stepWith A_m s_mir prog_mir = mirlite.Result.Ok s_mir_next) :
  ∃ ap',
    sb_use_mb s_mir.ap (addr + ctx.off) tag = SBResult.Ok ap' ∧
    s_mir_next =
      { s_mir with
        ap := ap',
        mem := mirlite.writeWordSeq s_mir.mem (addr + ctx.off) [mirlite.MemValue.Val ctx.n],
        pc := s_mir.pc + 1 } := by
  have h_stmt_mir : prog_mir.get? s_mir.pc = some ctx.stmt := StartsAt.singleton h_start
  rcases List.get?_eq_some_iff.mp h_stmt_mir with ⟨h_pc_mir, h_get_mir⟩
  unfold mirlite.stepWith at h_step
  rw [dif_pos h_pc_mir, h_get_mir] at h_step
  simp [ConstExistingCtx.stmt, obseq.notation.placeExpr, obseq.notation.constRhs,
    mirlite.stepAssignConstWith] at h_step
  rw [finishPlaceAssignWith_existing_eq h_env ctx.h_path] at h_step
  cases h_use : sb_use_mb s_mir.ap (addr + ctx.off) tag with
  | Err _ =>
      simp [h_use] at h_step
  | Ok ap' =>
      refine ⟨ap', rfl, ?_⟩
      simpa [h_use] using h_step.symm

variable (ctx : ConstExistingCtx)
variable (s_mir : mirlite.State)
variable (s_osea : oseair.State)
variable (s_mir_next : mirlite.State)
variable (ρa : AddrRenameMap)
variable (ρt : TagRenameMap)

theorem simulation
  (prog_mir : mirlite.Prog)
  (prog_osea : oseair.Prog)
  (h_sim : LocalSim ctx ρa ρt s_mir s_osea)
  (h_mir_start : StartsAt prog_mir s_mir.pc [ctx.stmt])
  (h_osea_start : StartsAt prog_osea s_osea.pc ctx.compiled)
  (h_mir_step : mirlite.stepWith A_m s_mir prog_mir = mirlite.Result.Ok s_mir_next) :
  ∃ s_osea_next,
    StepStarWith A_o s_osea prog_osea s_osea_next ∧
    LocalSim ctx ρa ρt s_mir_next s_osea_next := by
  let ⟨addr_m, addr_o, tag_m, tag_o, h_ptr, _h_block⟩ :=
    StateSim.place_projected h_sim ctx.h_lookup ctx.h_path
  have h_env := place_runtime_sim.env h_ptr
  have h_fit : ctx.off + blockSize LayoutTy.NatL ≤ blockSize ctx.baseLayout :=
    layoutResolvePath_blockSize_le ctx.h_path
  let ⟨ap_m', h_use, h_next_full⟩ :=
    mirlite_step_inv ctx s_mir s_mir_next prog_mir addr_m tag_m h_env h_mir_start h_mir_step
  have h_tmp_fresh :
      ∀ base layout, ctx.cs.placeMap.lookup base = some (ctx.tmpReg, layout) → False :=
    fun base layout h_lookup => alloc_fresh_reg (cs := ctx.cs) base layout h_lookup
  exact existing_write_simulation h_sim h_ptr h_fit (by decide) h_tmp_fresh
    (fun h_off => by simpa [ctx.compiled_eq, h_off] using h_osea_start)
    (fun h_off => by simpa [ctx.compiled_eq, h_off] using h_osea_start)
    h_use h_next_full (mem_vals_eq_word ctx.n) rfl

end ConstExisting

end obseq.proof
