import obseq2.compile
import obseq2.mirlite_semantics
import obseq2.permission

namespace obseq2.proof

open obseq2
open obseq2.compile
open obseq2.oseair (Instr Register Rhs Val)

/-- Clear the code map of a compiler state, leaving allocation counters unchanged. -/
def resetCode (cs : CompilerState) : CompilerState :=
  { cs with code := fun _ => none }

/-- Compile the first `pc` statements of `prog` starting from initial state `cs0`,
    returning the accumulated compiler state (including generated instructions). -/
def prefixCompileState
  {Γ : Ctx}
  (cs0 : CompilerState)
  (prog : obseq2.Prog Γ)
  (pc : Nat) : CompilerState :=
  List.foldl compileStmt cs0 (prog.take pc)

/-- The compiler state at the start of source statement `pc`: the result of compiling
    the prefix of length `pc`, with the instruction buffer reset to empty. -/
def csAt
  {Γ : Ctx}
  (cs0 : CompilerState)
  (prog : obseq2.Prog Γ)
  (pc : Nat) : CompilerState :=
  prefixCompileState cs0 prog pc

/-- The target program counter corresponding to source statement `pc`: the number of
    target instructions generated by compiling the first `pc` source statements. -/
def targetPcAt
  {Γ : Ctx}
  (cs0 : CompilerState)
  (prog : obseq2.Prog Γ)
  (pc : Nat) : Nat :=
  (prefixCompileState cs0 prog pc).nextLabel

/-- Compile an entire program starting from `cs0`, returning the target code map. -/
def compileProgFrom
  {Γ : Ctx}
  (cs0 : CompilerState)
  (prog : obseq2.Prog Γ) : obseq2.oseair.Prog :=
  (List.foldl compileStmt cs0 prog).code

theorem emit_code_lt_nextLabel
    (cs : CompilerState) (instrs : List Instr) {pc : Nat}
    (h : pc < cs.nextLabel) :
    (emit cs instrs).code pc = cs.code pc := by
  simp [emit, Nat.not_le_of_gt h]

theorem emit_nextLabel_ge
    (cs : CompilerState) (instrs : List Instr) :
    cs.nextLabel ≤ (emit cs instrs).nextLabel := by
  simp [emit]

theorem take_succ_eq_take_append_get
    {xs : List α} {n : Nat} {x : α}
    (h_get : xs.get? n = some x) :
    xs.take (n + 1) = xs.take n ++ [x] := by
  induction xs generalizing n with
  | nil =>
      cases n <;> cases h_get
  | cons y ys ih =>
      cases n with
      | zero =>
          simp [List.get?] at h_get
          cases h_get
          simp
      | succ n =>
          simp [List.get?] at h_get ⊢
          exact ih h_get

theorem drop_eq_get_cons
    {xs : List α} {n : Nat} {x : α}
    (h_get : xs.get? n = some x) :
    xs.drop n = x :: xs.drop (n + 1) := by
  induction xs generalizing n with
  | nil =>
      cases n <;> cases h_get
  | cons y ys ih =>
      cases n with
      | zero =>
          simp at h_get
          cases h_get
          simp
      | succ n =>
          simp [List.get?, List.drop] at h_get ⊢
          exact ih h_get

theorem prefixCompileState_succ
    {Γ : Ctx}
    {cs0 : CompilerState}
    {prog : obseq2.Prog Γ}
    {pc : Nat}
    {stmt : Stmt Γ}
    (h_get : prog.get? pc = some stmt) :
    prefixCompileState cs0 prog (pc + 1) =
      compileStmt (prefixCompileState cs0 prog pc) stmt := by
  rw [prefixCompileState, prefixCompileState]
  rw [take_succ_eq_take_append_get h_get]
  simp [List.foldl_append]

/-- The compiler state only grows: `nextLabel` and `nextReg` increase monotonically,
    and code slots below the old `nextLabel` are unchanged. -/
structure StateIncr (s1 s2 : CompilerState) : Prop where
  nextLabel_le : s1.nextLabel ≤ s2.nextLabel
  nextReg_le   : s1.nextReg ≤ s2.nextReg
  code_eq      : ∀ pc, pc < s1.nextLabel → s2.code pc = s1.code pc

theorem StateIncr.refl (cs : CompilerState) : StateIncr cs cs :=
  ⟨Nat.le_refl _, Nat.le_refl _, fun _ _ => rfl⟩

theorem StateIncr.trans {s1 s2 s3 : CompilerState}
    (h12 : StateIncr s1 s2) (h23 : StateIncr s2 s3) : StateIncr s1 s3 :=
  ⟨Nat.le_trans h12.nextLabel_le h23.nextLabel_le,
   Nat.le_trans h12.nextReg_le h23.nextReg_le,
   fun pc hpc =>
     (h23.code_eq pc (Nat.lt_of_lt_of_le hpc h12.nextLabel_le)).trans (h12.code_eq pc hpc)⟩

theorem emit_state_incr (cs : CompilerState) (instrs : List Instr) :
    StateIncr cs (emit cs instrs) :=
  ⟨emit_nextLabel_ge cs instrs, Nat.le_refl _,
   fun pc hpc => @emit_code_lt_nextLabel cs instrs pc hpc⟩

theorem freshReg_state_incr (cs : CompilerState) :
    StateIncr cs (freshReg cs).2 :=
  ⟨Nat.le_refl _, Nat.le_succ _, fun _ _ => rfl⟩

theorem placeToReg_state_incr
    {Γ : Ctx} {τ : LayoutTy}
    (cs : CompilerState) (kind : RefKind) (p : Place Γ τ) :
    StateIncr cs (placeToReg cs kind p).cs := by
  induction p generalizing cs kind with
  | «local» loc =>
      exact StateIncr.refl _
  | proj base path ih =>
      by_cases hoff : pathOffset path = 0
      · simpa [placeToReg, hoff] using ih cs kind
      · exact (ih cs kind).trans <|
            by simpa [placeToReg, hoff, freshReg] using
              (freshReg_state_incr (placeToReg cs kind base).cs).trans
                (emit_state_incr _ _)
  | deref ptrPlace ih =>
      exact (ih cs RefKind.Shared).trans <|
          by simpa [placeToReg, freshReg] using
            (freshReg_state_incr (placeToReg cs RefKind.Shared ptrPlace).cs).trans
              ((emit_state_incr _ _).trans (emit_state_incr _ _))

theorem placeToBorrowReg_state_incr
    {Γ : Ctx} {τ : LayoutTy}
    (cs : CompilerState) (kind : RefKind) (p : Place Γ τ) :
    StateIncr cs (placeToBorrowReg cs kind p).cs := by
  cases p with
  | «local» loc =>
      simpa [placeToBorrowReg, freshReg] using
        (freshReg_state_incr cs).trans (emit_state_incr _ _)
  | proj base path =>
      exact (placeToReg_state_incr cs kind base).trans <|
          by simpa [placeToBorrowReg, freshReg] using
            (freshReg_state_incr (placeToReg cs kind base).cs).trans
              (emit_state_incr _ _)
  | deref ptrPlace =>
      exact (placeToReg_state_incr cs RefKind.Shared ptrPlace).trans <|
          by simpa [placeToBorrowReg, freshReg] using
            (freshReg_state_incr (placeToReg cs RefKind.Shared ptrPlace).cs).trans
              ((emit_state_incr _ _).trans
               ((emit_state_incr _ _).trans
                ((freshReg_state_incr _).trans (emit_state_incr _ _))))

theorem compileRExprTo_state_incr
    {Γ : Ctx} {τ : LayoutTy}
    (cs : CompilerState) (dstPtr : Register) (expr : RExpr Γ τ) :
    StateIncr cs (compileRExprTo cs dstPtr expr) := by
  cases expr with
  | constInit value =>
      simpa [compileRExprTo] using emit_state_incr cs _
  | copy src =>
      exact (placeToReg_state_incr cs RefKind.Shared src).trans <|
          by simpa [compileRExprTo] using
            emit_state_incr (placeToReg cs RefKind.Shared src).cs _
  | ref kind src =>
      exact (placeToBorrowReg_state_incr cs kind src).trans <|
          by simpa [compileRExprTo] using
            emit_state_incr (placeToBorrowReg cs kind src).cs _

theorem compileStmt_state_incr
    {Γ : Ctx}
    (cs : CompilerState) (stmt : Stmt Γ) :
    StateIncr cs (compileStmt cs stmt) := by
  cases stmt with
  | halt =>
      simpa [compileStmt] using emit_state_incr cs _
  | assign dst rhs =>
      refine (placeToReg_state_incr cs RefKind.Mut dst).trans
        ((compileRExprTo_state_incr (placeToReg cs RefKind.Mut dst).cs
            (placeToReg cs RefKind.Mut dst).reg rhs).trans ?_)
      simpa [compileStmt] using
        emit_state_incr
          (compileRExprTo (placeToReg cs RefKind.Mut dst).cs
            (placeToReg cs RefKind.Mut dst).reg rhs)
          (cleanupInstrs (placeToReg cs RefKind.Mut dst).cleanup)

theorem foldl_compileStmt_state_incr
    {Γ : Ctx}
    (cs : CompilerState) (prog : obseq2.Prog Γ) :
    StateIncr cs (List.foldl compileStmt cs prog) := by
  induction prog generalizing cs with
  | nil => exact StateIncr.refl _
  | cons stmt rest ih =>
      exact (compileStmt_state_incr cs stmt).trans (ih (compileStmt cs stmt))

theorem compileProgFrom_code_eq_compileStmt
    {Γ : Ctx}
    (cs0 : CompilerState) (prog : obseq2.Prog Γ) {pc : Nat} {stmt : Stmt Γ}
    (h_get : prog.get? pc = some stmt)
    {q : Nat}
    (h_lt : q < (compileStmt (csAt cs0 prog pc) stmt).nextLabel) :
    compileProgFrom cs0 prog q =
      (compileStmt (csAt cs0 prog pc) stmt).code q := by
  have h_decomp :
      (List.foldl compileStmt cs0 prog).code q =
        (List.foldl compileStmt (prefixCompileState cs0 prog pc) (prog.drop pc)).code q := by
    change (List.foldl compileStmt cs0 prog).code q =
      (List.foldl compileStmt (List.foldl compileStmt cs0 (prog.take pc)) (prog.drop pc)).code q
    calc
      (List.foldl compileStmt cs0 prog).code q =
          (List.foldl compileStmt cs0 (prog.take pc ++ prog.drop pc)).code q := by
            exact congrArg (fun xs => (List.foldl compileStmt cs0 xs).code q)
              (List.take_append_drop pc prog).symm
      _ = (List.foldl compileStmt (List.foldl compileStmt cs0 (prog.take pc)) (prog.drop pc)).code q := by
            rw [List.foldl_append]
  unfold compileProgFrom
  rw [h_decomp, drop_eq_get_cons h_get]
  simp only [List.foldl_cons]
  simpa [csAt, prefixCompileState] using
    (foldl_compileStmt_state_incr
      (compileStmt (prefixCompileState cs0 prog pc) stmt)
      (prog.drop (pc + 1))).code_eq q h_lt

/- Supporting lemmas needed later:
- `freshReg` preserves all old register bounds and introduces one fresh bounded register.
- `emit` preserves `InstrsRegsBelow` when the appended fragment is bounded.
- `cleanupInstrs` only emits `Die` instructions over already bounded registers.
- `placeToReg` and `placeToBorrowReg` preserve `CompilerStateWF`.
- `compileRExprTo`, `compileRExpr`, `compileStmt`, and `prefixCompileState` preserve `CompilerStateWF`.
- `initLocals` establishes the local-pointer shape expected by `TargetLocalsReady`.
- `targetPcAt` agrees with actual execution of the compiled prefix.
- End-of-write obligation: for every `RStore ty src ptr` or `CStore ty vals ptr` emitted by the
  compiler, `vals.length = typeSize ty` and the destination pointer satisfies
  `offset + typeSize ty ≤ size`. This is derived from MIRLite's type-system guarantee
  (`Place.offset + blockSize τ ≤ blockSize σ`) and must be proved as part of `CompiledWF`.
  `writeThroughPtr` only checks `addr >= base + size` (start-of-write), matching MIRLite's own
  lack of an explicit bounds check; the end-of-write safety is a static obligation, not a
  runtime one.
-/
/-- A register whose numeric index is strictly less than `bound`. -/
def RegisterBelow (bound : Nat) : Register → Prop
  | .R idx => idx < bound

/-- All registers mentioned in an `Rhs` have index strictly less than `bound`. -/
def RhsRegsBelow (bound : Nat) : Rhs → Prop
  | .Load _ reg => RegisterBelow bound reg
  | .Alloc _ => True
  | .BorOffset base _ => RegisterBelow bound base
  | .MutBorOffset base _ => RegisterBelow bound base
  | .CopyOffset base _ => RegisterBelow bound base
  | .BinOp lhs rhs => RegisterBelow bound lhs ∧ RegisterBelow bound rhs

/-- All registers mentioned in an `Instr` have index strictly less than `bound`. -/
def InstrRegsBelow (bound : Nat) : Instr → Prop
  | .Assgn reg rhs => RegisterBelow bound reg ∧ RhsRegsBelow bound rhs
  | .RStore _ src ptr => RegisterBelow bound src ∧ RegisterBelow bound ptr
  | .CStore _ _ ptr => RegisterBelow bound ptr
  | .Memcpy dst src _ => RegisterBelow bound dst ∧ RegisterBelow bound src
  | .Die reg => RegisterBelow bound reg
  | .Halt => True

/-- Every populated code slot satisfies `InstrRegsBelow bound`. -/
def CodeRegsBelow (bound : Nat) (code : Nat → Option Instr) : Prop :=
  ∀ pc instr, code pc = some instr → InstrRegsBelow bound instr

/-- A well-formed compiler state for context `Γ`:
    - `nextReg` is at least as large as the number of locals (so local registers don't alias fresh temporaries).
    - Every emitted instruction only references registers below `nextReg`. -/
def CompilerStateWF (Γ : Ctx) (cs : CompilerState) : Prop :=
  Γ.length ≤ cs.nextReg ∧ CodeRegsBelow cs.nextReg cs.code

/-- Register `reg` in `regMap` holds a pointer value with the given `base` address,
    `offset`, `size`, and `tag`. -/
def PtrRegisterEntry
  (regMap : obseq2.oseair.RegMap)
  (reg : Register)
  (base offset size : Word)
  (tag : Tag) : Prop :=
  obseq2.oseair.RegMap.lookup regMap reg = some (obseq.TyVal.PTy, [Val.Ptr base offset size tag])

/- Supporting lemmas needed later:
- running `initLocals` produces a `PtrRegisterEntry` for every `localReg` with offset `0`
  and block size `blockSize τ`.
- executing compiled statements preserves the local base-pointer entries for unrelated locals.
-/
/-- Every local variable in `Γ` has a corresponding pointer register in the target state
    at offset 0 with the correct block size for its layout type. -/
def TargetLocalsReady (Γ : Ctx) (s_osea : obseq2.oseair.State) : Prop :=
  ∀ {τ : LayoutTy} (loc : Local Γ τ),
    ∃ base tag,
      PtrRegisterEntry s_osea.reg (localReg loc) base 0 (blockSize τ) tag

/- Supporting lemmas needed later:
- `initLocals` aligns each source local with its target `localReg` base pointer.
- direct source allocation updates `LocalBindingSim` only at the assigned local.
- target-side pointer tags created by compiled `ref` fragments respect the tag rename map.
-/
/-- Simulation relation between source local bindings and target register values.
    For every local `loc` with source binding `binding`, the target holds a pointer register
    at `localReg loc` whose base and tag are the images of `binding.addr` and `binding.tag`
    under the rename maps `ρa` and `ρt` respectively. -/
def LocalBindingSim
  {Γ : Ctx}
  (ρa : AddrRenameMap)
  (ρt : TagRenameMap)
  (env : obseq2.mirlite.Env Γ)
  (s_osea : obseq2.oseair.State) : Prop :=
  ∀ {τ : LayoutTy} (loc : Local Γ τ) (binding : obseq2.mirlite.Binding),
    obseq2.mirlite.Env.lookup env loc = some binding →
    ∃ base tag,
      PtrRegisterEntry s_osea.reg (localReg loc) base 0 (blockSize τ) tag ∧
      ρa binding.addr = some base ∧
      ρt binding.tag = some tag

/- Supporting lemmas needed later:
- source reads from allocated blocks correspond to target reads at renamed addresses.
- source writes preserve `MemValSim` at unaffected addresses.
- `ptrVal` stored by `ref` corresponds to `Val.Ptr` in the target under the rename maps.
-/
/-- Pointwise simulation between a source `MemValue` and a target `Val`.
    With the concrete pointer representation (Option B), env is no longer needed here:
    - `undef`   ↔ `Undef`
    - `word v`  ↔ `Dat v`       (value equality)
    - `ptrVal b o s t` ↔ `Ptr b' o s t'`  (base renamed by ρa, tag renamed by ρt,
                                             offset and size equal) -/
def MemValSim
  (ρa : AddrRenameMap)
  (ρt : TagRenameMap) : obseq2.mirlite.MemValue → Val → Prop
  | .undef,           .Undef             => True
  | .word v,          .Dat v'            => v' = v
  | .ptrVal b o s t,  .Ptr b' o' s' t'  =>
      ρa b = some b' ∧ o' = o ∧ s' = s ∧ ρt t = some t'
  | _, _                                 => False

/- Supporting lemmas needed later:
- source memory inclusion is enough for the current fragment because target `initLocals`
  allocates local blocks before the source semantics allocate them on first assignment.
- compiled `Memcpy`, `CStore`, and `RStore` fragments preserve `SourceMemSim` at renamed addresses.
-/
/-- For every address/value pair present in the source memory, there exists a corresponding
    renamed address in the target memory whose value is related by `MemValSim`.
    `env` is no longer a parameter — `MemValSim` is self-contained with the concrete pointer repr. -/
def SourceMemSim
  (ρa : AddrRenameMap)
  (ρt : TagRenameMap)
  (mem_mir : obseq2.mirlite.Mem)
  (mem_osea : obseq2.oseair.Mem) : Prop :=
  ∀ addr value,
    obseq2.mirlite.Mem.find? mem_mir addr = some value →
    ∃ addr' value',
      ρa addr = some addr' ∧
      obseq2.oseair.Mem.find? mem_osea addr' = some value' ∧
      MemValSim ρa ρt value value'

/- Blocking factors for stronger invariants:
- a generic permission-state relation is not definable yet because the target runtime stores
  concrete stacked-borrows permissions in `oseair.State`, while `mirlite.State` is abstract
  over `PermissionModel`; this scaffold therefore specializes the source side to
  `PermissionModel.stackedBorrows`.
- a bidirectional memory relation is premature because target initialization allocates all
  locals eagerly, while source allocation is deferred to direct local assignment.
- temp-register ownership produced by `placeToReg` and `placeToBorrowReg` is not included in
  `CompilerInv` yet because the required preservation lemmas are still missing.
-/
/-- The main simulation invariant between a source `mirlite` state and a target `oseair` state.
    Asserts:
    - PC agreement: `s_osea.pc = targetPcAt cs0 prog s_mir.pc`.
    - Well-formedness of the compiled prefix's compiler state.
    - All locals have valid pointer registers in the target (`TargetLocalsReady`).
    - Source local bindings are simulated by target registers (`LocalBindingSim`).
    - Source memory is forward-simulated in target memory (`SourceMemSim`).
    - Permission states are equal. -/
def CompilerInv
  {Γ : Ctx}
  (cs0 : CompilerState)
  (prog : obseq2.Prog Γ)
  (ρa : AddrRenameMap)
  (ρt : TagRenameMap)
  (s_mir : obseq2.mirlite.State PermissionModel.stackedBorrows Γ)
  (s_osea : obseq2.oseair.State) : Prop :=
  s_osea.pc = targetPcAt cs0 prog s_mir.pc ∧
  CompilerStateWF Γ (prefixCompileState cs0 prog s_mir.pc) ∧
  TargetLocalsReady Γ s_osea ∧
  LocalBindingSim ρa ρt s_mir.env s_osea ∧
  SourceMemSim ρa ρt s_mir.mem s_osea.mem ∧
  s_osea.ap = s_mir.perms ∧
  PermissionModel.stackedBorrows.WellFormed s_mir.perms

-- Register `reg` holds a pointer to `resolved`, and the tag stored there has
-- mutable write permission at the target address in `s_ap`.
--
-- The tag t' in the register is NOT necessarily ρt(resolved.tag):
--   local   : t' = ρt(resolved.tag), from LocalBindingSim.
--   proj    : t' is a fresh borrow created by MutBorOffset/BorOffset; it has
--             write permission in s_ap because sb_ref just pushed it onto the stack.
--   deref   : t' is whatever was stored in the pointer cell; writability comes
--             from the reference creation that stored it.
-- In all cases, write permission is captured by the `useMut` conjunct rather than
-- a static tag-rename relation.
def PlaceRegReady
    (ρa : AddrRenameMap)
    (s_ap : AccessPerms)
    (regMap : oseair.RegMap)
    (reg : Register)
    (resolved : obseq2.mirlite.PlaceRes) : Prop :=
  ∃ (b' : Word) (t' : Tag),
    ρa resolved.allocBase = some b' ∧
    PtrRegisterEntry regMap reg b' (resolved.addr - resolved.allocBase) resolved.allocSize t' ∧
    ∃ ap2,
      PermissionModel.stackedBorrows.useMut s_ap
        (b' + (resolved.addr - resolved.allocBase)) t' = some ap2

-- Core place correspondence lemma.
-- Proof plan (induction on p):
--   local loc    : frag=[]; LocalBindingSim gives PtrRegisterEntry for localReg loc directly.
--   proj base path (offset=0) : no new instruction; IH on base suffices.
--   proj base path (offset>0) : IH on base; one BorOffset/MutBorOffset/CopyOffset
--     executes; bounds hold by PathTo type invariant; sb_ref creates fresh borrow tag.
--   deref ptrPlace : IH on ptrPlace; Die cleans up inner tmps; Load reads Val.Ptr from
--     target mem; SourceMemSim+MemValSim give base/offset/size correspondence.
theorem placeToReg_correct
    {Γ : Ctx} {τ : LayoutTy}
    (cs : CompilerState) (kind : RefKind) (p : Place Γ τ)
    {ρa : AddrRenameMap} {ρt : TagRenameMap}
    {s_mir : obseq2.mirlite.State PermissionModel.stackedBorrows Γ}
    {s_osea : oseair.State}
    (compProg : oseair.Prog)
    (h_lbs : LocalBindingSim ρa ρt s_mir.env s_osea)
    (h_sms : SourceMemSim ρa ρt s_mir.mem s_osea.mem)
    (h_wf  : CompilerStateWF Γ cs)
    (h_ap  : PermissionModel.stackedBorrows.WellFormed s_osea.ap)
    (h_slice : ∀ (i : Fin ((placeToReg cs kind p).cs.nextLabel - cs.nextLabel)),
        compProg (s_osea.pc + i.1) =
        (placeToReg cs kind p).cs.code (cs.nextLabel + i.1))
    {resolved : obseq2.mirlite.PlaceRes}
    (h_res : obseq2.mirlite.resolvePlace? s_mir p = some resolved) :
    ∃ s_osea',
      oseair.runN ((placeToReg cs kind p).cs.nextLabel - cs.nextLabel)
        s_osea compProg = oseair.Result.Ok s_osea' ∧
      PlaceRegReady ρa s_osea'.ap s_osea'.reg (placeToReg cs kind p).reg resolved ∧
      s_osea'.mem = s_osea.mem ∧
      s_osea'.pc = s_osea.pc +
        ((placeToReg cs kind p).cs.nextLabel - cs.nextLabel) ∧
      ∀ r, RegisterBelow cs.nextReg r →
        s_osea'.reg.lookup r = s_osea.reg.lookup r := by
  induction p generalizing cs s_osea with
  | «local» loc =>
      -- frag = []; result.reg = localReg loc.
      -- LocalBindingSim gives PtrRegisterEntry with ρa binding.addr = b'.
      -- resolved = { addr := binding.addr, allocBase := binding.addr,
      --   allocSize := blockSize τ, tag := binding.tag }.
      -- PlaceRegReady holds: offset = addr - allocBase = 0.
      sorry
  | proj base path ih =>
      -- resolvePlace? (.proj base path) = some { resolvedBase with
      --   addr := resolvedBase.addr + PathTo.offset path }
      by_cases hoff : pathOffset path = 0
      · -- offset 0: placeToReg returns baseRes unchanged; IH on base suffices.
        sorry
      · -- offset > 0: IH on base gives baseRes.reg; one BorOffset/MutBorOffset/CopyOffset
        --   instruction runs; bounds hold by PathTo type invariant; fresh borrow tag created.
        sorry
  | deref ptrPlace ih =>
      -- IH on ptrPlace gives ptrRes.reg holding pointer to ptr cell.
      -- Die instructions clean up inner temporaries.
      -- Load reads Val.Ptr from target mem; SourceMemSim+MemValSim close the correspondence.
      sorry

-- Simulation lemma for a single-word write: if source writeResolvedPlace succeeds
-- and the target register holds a suitably renamed pointer (PlaceRegReady), then
-- writeThroughPtr succeeds and memory simulation is preserved.
--
-- Key correspondences required (proved via sorry for now):
--   (1) bounds: resolved.addr + 1 ≤ allocBase + allocSize
--               ↔ (b' + offset) + 1 ≤ b' + size
--       (arithmetic; needs ρa(base + k) = ρa(base) + k within allocations)
--   (2) permission: PlaceRegReady already contains ∃ ap2, useMut s_osea.ap addr' t' = some ap2;
--       no separate ρt tag-rename needed.
--   (3) memory: writeWordSeq at b'+offset corresponds to source writeWordSeq at resolved.addr;
--       MemValSim (word v) (Dat v) extends SourceMemSim at the written cell.
--
-- Note: s_osea'.ap is the post-write ap (from sb_use_mb).  The full ap correspondence
-- s_osea_final.ap = s_mir'.perms is restored by the Die cleanup phase, not here.
theorem writeThroughPtr_sim
    {Γ : Ctx}
    (ρa : AddrRenameMap) (ρt : TagRenameMap)
    {s_mir  : obseq2.mirlite.State PermissionModel.stackedBorrows Γ}
    {s_mir' : obseq2.mirlite.State PermissionModel.stackedBorrows Γ}
    {s_osea : oseair.State}
    {resolved : obseq2.mirlite.PlaceRes}
    {dstReg : Register}
    (v : Word)
    (h_ptr   : PlaceRegReady ρa s_osea.ap s_osea.reg dstReg resolved)
    (h_sms   : SourceMemSim ρa ρt s_mir.mem s_osea.mem)
    (h_write : obseq2.mirlite.writeResolvedPlace (τ := obseq.LayoutTy.NatL)
                 PermissionModel.stackedBorrows s_mir resolved
                 [obseq2.mirlite.MemValue.word v] rfl
               = obseq2.mirlite.Result.ok s_mir') :
    ∃ s_osea',
      oseair.writeThroughPtr s_osea dstReg [Val.Dat v] "CStore Invalid Ptr"
        = oseair.Result.Ok s_osea' ∧
      SourceMemSim ρa ρt s_mir'.mem s_osea'.mem ∧
      s_osea'.reg = s_osea.reg ∧
      s_osea'.pc = s_osea.pc + 1 := by
  sorry

-- A CStore instruction at position s.pc in compProg, with vals.length = typeSize ty,
-- executes as a single runN step via writeThroughPtr.
theorem runN_CStore_step
    (compProg : oseair.Prog) (s s' : oseair.State)
    (ty : obseq.TyVal) (vals : List Val) (ptr : Register)
    (h_instr : compProg s.pc = some (Instr.CStore ty vals ptr))
    (h_size : vals.length = obseq.typeSize ty)
    (h_wtp : oseair.writeThroughPtr s ptr vals "CStore Invalid Ptr" = oseair.Result.Ok s') :
    oseair.runN 1 s compProg = oseair.Result.Ok s' := by
  sorry

-- Running cleanupInstrs dies (a sequence of Die instructions) from s in compProg
-- succeeds and leaves mem and reg unchanged, advancing pc by the cleanup length.
-- Die-succeeds relies on ap coherence after useMut; that obligation is deferred.
theorem runN_cleanupInstrs
    (compProg : oseair.Prog) (s : oseair.State) (dies : List Register)
    (h_instrs : ∀ (i : Fin (cleanupInstrs dies).length),
      compProg (s.pc + i.1) = some ((cleanupInstrs dies).get i)) :
    ∃ s' : oseair.State,
      oseair.runN (cleanupInstrs dies).length s compProg = oseair.Result.Ok s' ∧
      s'.mem = s.mem ∧ s'.reg = s.reg ∧ s'.pc = s.pc + (cleanupInstrs dies).length := by
  sorry

-- runN is composable: running m steps then n more equals m+n steps.
theorem oseair_runN_add
    (m n : Nat) (s : oseair.State) (prog : oseair.Prog) (s' : oseair.State)
    (h : oseair.runN m s prog = oseair.Result.Ok s') :
    oseair.runN (m + n) s prog = oseair.runN n s' prog := by
  induction m generalizing s with
  | zero =>
      simp [oseair.runN] at h
      simp [oseair.runN, h]
  | succ m ih =>
      simp only [Nat.succ_add, oseair.runN, oseair.runNWith_succ] at *
      split at h
      · exact ih _ h
      · simp at h

end obseq2.proof
